### PR TITLE
Update Requirments :  .NET Framework

### PR DESCRIPTION
**Pull request by iamnotagentleman**

### CODE REVIEW

**Comment by SuperJMN** [comment]
Please, add the exact version. It requires 4.6.1 or greater :)

**Comment by SuperJMN** [comment]
Also, please, ensure that you use WOA Deployer. This project is obsolete :) 

👉 https://github.com/WOA-project/WOA-Deployer

**Comment by CornyjK** [comment]
> Please, add the exact version. It requires 4.6.1 or greater :)

Probably pointless PR, as we recommend to use latest version of Windows 10.

> Also, please, ensure that you use WOA Deployer. This project is obsolete :)

He is deploying a RPi.

**Comment by biconix** [comment]
is there a reason to redeploy Windows on the Lumia 950XL at this point?


_____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972(2) 590-0801

**Comment by SuperJMN** [comment]
I don't think so, but stay tuned. Soon we can have news. Subscribe to this channel for announcements and important info.

https:/t.me/LumiaWOA_Announcements

**Pull request closed without merging**
